"""empty message

Revision ID: 215504afa223
Revises: 0da61e42910d
Create Date: 2023-03-24 15:26:49.756426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215504afa223'
down_revision = '0da61e42910d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddit_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['threadit_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subreddit_members')
    # ### end Alembic commands ###
